Algoritmo "primeiroCodigo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Ele exibe uma mensagem na tela
// Autor(a)    : Pedro
// Data atual  : 31/12/2019
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval ("Pedro " + "Lindo")
Escreva ("Feliz Ano Novo")

Fimalgoritmo